_target_: tracklab.wrappers.PoseTrack21Evaluator

# Support 4 metrics:
# 1. Pose Estimation mAP
# 2. Keypoints HOTA
# 3. Bbox HOTA
# 4. Bbox MOTA
# Not supported in this repo: Keypoints MOTA + Person search (map - rank-1)
# Notes about issues with evaluation PoseTrack21 evaluation code:
# 1. Pose mAP was not working with their json because of we used the 'scores' from their keypoints filed, which contained binary scores (O or 1)
# But there is also a 'score' entry in their json containing the real continuous score. We used this one instead to fix the issue.
# 2. Keypoints HOTA was not working because we forgot to include their recovered detections, marked as 'new_anno=True' in their json.
# Because we didn't include these detections, performance were lower.
# 3. HOTA bbox: was not working because of printing issue, HOTA bbox saved to disk was correct.
# 4. MOTA bbox: we had less good performance with some video having negative MOTA. This happend because of ignore regions:
# the ignore_region flag must be set to true, which was not the case for our code. This is now fixed, but we still don't
#  have the same performance as them, we have +2% better MOTA (on CorrTrack,, Tracktor, ...), which is strange. We have these +2% even
# when using their Corrtrack .txt predictions with their evaluation code called directly ('python evaluate_mot.py ...')
# FIXME remaining issues to FIX:
#  - MOTA score is above paper results
#  - Some videos with ignored regions have negative MOTA

cfg:
  eval_pose_estimation: True
  eval_pose_tracking: True
  eval_reid_pose_tracking: False # Not working
  eval_mot: True

  keypoints_column_for_eval: "keypoints_xyc"  # which keypoints column to use for evaluation
  vis_kp_threshold: 0.3
  min_num_vis_kp: 3
  min_tracklet_length: 3
  bbox_column_for_eval: "bbox_ltwh"  # which bbox column to use for evaluation: {"bbox_ltwh", "track_bbox_kf_ltwh", ...}
  eval_pose_on_all: False  # Evaluation pose estimation on all detections. If set to false, will evaluate pose estimation only on tracked detections (i.e. detections with a defined 'track_id')
  print_by_video: False

  posetrack_trackers_folder: "eval/posetrack21"
  posetrack_gt_folder: ${dataset.annotation_path}/val

  mot_trackers_folder: "eval/mot"
  mot_gt_folder: ${dataset.dataset_path}/posetrack_mot/mot/val

  use_parallel: True
  num_parallel_cores: ${num_cores}

  mot:
    dataset_path: ${dataset.dataset_path}
    use_ignore_regions: True
    ignore_iou_thres: 0.1
    vis_threshold: 0.1
