defaults:
  - default

_target_: tracklab.wrappers.PoseTrack21

dataset_path: ${data_dir}/PoseTrack21
annotation_path: ${data_dir}/PoseTrack21/posetrack_data
eval_set: "val"

####### Interesting videos for PoseTrack21 #######
#
# Scenarios we need to cover:
# - close-up vs far away (= small vs big people)
# - multiple scales (small and large people in image)
# - occlusion
# - people with similar appearance
# - people with strange poses
# - diverse domains (sport, transportation, inside/outside, ...)
# - diverse camera angles (top, side, front, ...)
# - diverse camera types (phone, drone, television, ...)
# - diverse camera motion (static, moving, ...)
#
# Short list covering most of these scenarios with a lot of persons inside:
# ["016236_mpii_test", "024575_mpii_test", "016180_mpii_test", "024159_mpii_test"]
#
#  list of interesting videos with short description:
#  "001001_mpii_test",  # foot volleyball
#  "001735_mpii_test",  # cyclist outside with few occlusions
#  "002276_mpii_test",  # gymnastics lesson inside
#  "024907_mpii_test",  # bikers at differents scales
#  "024159_mpii_test",  # amateur basketball
#  "023962_mpii_test",  # fighters on the ground
#  "023717_mpii_test",  # la cross game with big camera switch
#  "022688_mpii_test",  # rugby with well visible players but a lot of interesting occlusions
#  "020880_mpii_test",  # race on ice with 2 camera switch and advertissement in first frames
#  "018898_mpii_test",  # physio therapy, no movements but hard poses
#  "018092_mpii_test",  # three camera switches, one view with no people, one view with a close up on a few heads
#  "018090_mpii_test",  # head close up, face tracking
#  "016236_mpii_test",  # football with well visible full body but a lot of interesting occlusions
#  "016180_mpii_test",  # video with a lot of people at different scales
#  "013293_mpii_test",  # partially occluded musicians
#  "012834_mpii_test",  # a lot of small people
#  "000522_mpii_test",  # 100m hurdle (haies) race
#  "004622_mpii_test",  # a lot of trampoline jumpers with similar appearance
#  "008827_mpii_test",  # rugby players, small people
#  "024575_mpii_test",  # dancers with similar appearance and occlusions
#  "009473_mpii_test",  # Two dancers with very similar appearance, heavily occluding each other + lot of ignore regions.
#  "015301_mpii_test",  # Fanfare walking from left to right, well visible, many people but easy to track.
#  "022691_mpii_test",  # Very interesting person occluded multiple times
