defaults:
  - dataset: default

_target_: tracklab.wrappers.BPBReId
training_enabled: False
batch_size: 32
job_id: "${oc.env:SLURM_JOBID,0}" # TODO
save_path: reid
use_keypoints_visibility_scores_for_reid: False
datasets: ${datasets}

cfg:
  project:
    name: "simformer_kpr"
    experiment_name: ""
    notes: ""
    tags: []
    job_id: ""
    logger:
      use_wandb: False
  data:
    save_dir: ""
