defaults:
  - dataset: default

_target_: tracklab.wrappers.KPReId
training_enabled: False
batch_size: 4
job_id: "${oc.env:SLURM_JOBID,0}" # TODO
save_path: reid
use_keypoints_visibility_scores_for_reid: False
cfg:
  project:
    name: "PbTrack"
    experiment_name: ""
    notes: ""
    tags: []
    logger:
      use_clearml: False
      use_tensorboard: False
      use_wandb: False
  data:
    root: '~/datasets/reid'
    type: "image"
    sources: ["PoseTrack21"]
    targets: ["PoseTrack21"]
    height: 256
    width: 128
    combineall: False
    transforms: ["rc", "re", "ro"]
    norm_mean: [0.485, 0.456, 0.406]
    norm_std: [0.229, 0.224, 0.225]
    save_dir: ""
    workers: ${num_cores}
    ro:
      p: 0.2
      n: 1
      pid_sampling_from_batch: False
      masks_dir: "pose_on_img_crops"

  sampler:
    train_sampler: RandomIdentitySampler # sampler for source train loader
    train_sampler_t: RandomIdentitySampler # sampler for target train loader
    num_instances: 4 # number of instances per identity for RandomIdentitySampler

  model:
    name: "bpbreid"
    pretrained: True
    save_model_flag: True
    load_weights: "${model_dir}/reid/job-42368286_sleek-music-1824_82mAP_92_r1.pth.tar"
    backbone_pretrained_path: '${model_dir}/reid'
    bpbreid:
      enable_fpn: False
      fpn_out_dim: 1024
      enable_msf: True
      pooling: "gwap" # ['gap', 'gmp', 'gwap', 'gwap2']
      normalization: "identity" # 'batch_norm_2d' 'identity'
      mask_filtering_training: False
      mask_filtering_testing: True
      training_binary_visibility_score: True
      testing_binary_visibility_score: True
      last_stride: 1
      learnable_attention_enabled: True
      dim_reduce: "after_pooling" # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
      dim_reduce_output: 512
      backbone: "swinv2_base_window12to16_192to256.ms_in22k_ft_in1k" # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
      test_embeddings: ["bn_foreg", "parts"] #  ['globl', 'foreg', 'conct', 'parts']
      use_prompt_visibility_score: False
      test_use_target_segmentation: "none" # 'none' 'hard' 'soft'
      shared_parts_id_classifier: False
      keypoints:
        enabled: True
        vis_thresh: 0.3
        vis_continous: False
        use_negative_keypoints: True
        prompt_masks: keypoints_gaussian # none, keypoints, keypoints_gaussian, gaussian, joints_gaussian
        prompt_preprocess: cck8  # "cck6" or "ccj6"
        target_masks: none # none, keypoints, keypoints_gaussian, gaussian, joints_gaussian
        target_preprocess: none  # "cck6" or "ccj6"
      masks:
        enabled: True
        type: "disk"
        dir: "${.....dataset.masks_mode}" # relative import, with a lot of indirection
        preprocess: "eight"
    vit:
      no_background_token: False
      masks_prompting: True
      disable_inference_prompting: False  # FIXME use DKRT
      pose_encoding_strategy: 'embed_heatmaps_patches'  # 'embed_heatmaps_patches', 'spatialize_part_tokens'
      pose_encoding_all_layers: False
    transreid:
      sie_camera: False

  loss:
    name: 'part_based'
    part_based:
      name: 'part_averaged_triplet_loss'
      ppl: 'cl'
      weights:
        globl:
          id: 1.
          tr: 0.
        foreg:
          id: 1.
          tr: 0.
        conct:
          id: 1.
          tr: 0.
        parts:
          id: 0.
          tr: 1.
        pixls:
          ce: 0.35

  train:
    batch_size: 64
    max_epoch: 120
    optim: "sgd"
    lr: 0.008  # TODO /!\ often vary depending on TransReID model
    warmup_t: 5  # default: 5, Solider: 20
    weight_decay: 1e-4
    weight_decay_bias: 1e-4
    base_lr_mult: 2.0
    lr_scheduler: "cosine_annealing_warmup"  # 'warmup_multi_step', 'cosine_annealing', 'cosine_annealing_warm_restarts'
    transreid_lr: True
    gamma: 0.1  # learning rate decay multiplier
    mixed_precision: True

  test:
    evaluate: False
    detailed_ranking: False
    start_eval: 40
    batch_size: 100
    batch_size_pairwise_dist_matrix: 5000
    normalize_feature: True
    dist_metric: "euclidean" # ['euclidean', 'cosine']
    visrank: True
    visrank_per_body_part: False
    vis_embedding_projection: False
    vis_feature_maps: False
    visrank_topk: 10
    visrank_count: 10
    visrank_q_idx_list: []
    part_based:
      dist_combine_strat: mean
