defaults:
  - default

_target_: tracklab.wrappers.SoccerNetMOT

dataset_path: ${data_dir}/SoccerNetMOT
annotation_path: ${data_dir}/SoccerNetMOT
eval_set: "val"

track_eval:
  dataset_class: MotChallenge2DBox
  GT_FOLDER: "eval/gt" # Location of GT data
  GT_LOC_FORMAT: '{gt_folder}/{seq}.txt' # '{gt_folder}/{seq}/gt/gt.txt'
  TRACKERS_FOLDER: 'eval/pred' # Trackers location
  TRACKER_SUB_FOLDER: '' # Tracker files are in TRACKER_FOLDER/tracker_name/TRACKER_SUB_FOLDER
  OUTPUT_FOLDER: "eval/results" # Where to save eval results (if None, same as TRACKERS_FOLDER)
  OUTPUT_SUB_FOLDER: '' # Output files are saved in OUTPUT_FOLDER/tracker_name/OUTPUT_SUB_FOLDER
  SPLIT_TO_EVAL: ${dataset.eval_set}
  PRINT_CONFIG: False
  DO_PREPROC: False
  TRACKER_DISPLAY_NAMES: null
  EVAL_SPACE: 'pitch'
  USE_JERSEY_NUMBERS: True
  USE_TEAMS: True
  USE_ROLES: True
